server:
  port: 8082
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    net.devh.boot.grpc: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

  file:
    name: 'gateway.log'


---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  graphql:
    graphiql:
      enabled: true

grpc:
  client:
    GLOBAL:
      max-inbound-message-size: 9999999999
    grpcGeoClient:
      address: 'static://localhost:8086'
      negotiationType: PLAINTEXT
    grpcPhotoClient:
      address: 'static://localhost:8096'
      negotiationType: PLAINTEXT
    grpcUserClient:
      address: 'static://localhost:8090'
      negotiationType: PLAINTEXT


rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8089'
rangiffler-photo:
  base-uri: 'http://127.0.0.1:8095'
rangiffler-geo:
  base-uri: 'http://127.0.0.1:8085'
rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rangiffler.dc:9000'

grpc:
  client:
    GLOBAL:
      max-inbound-message-size: 9999999999
    grpcGeoClient:
      address: 'static://geo.rangiffler.dc:8086'
      negotiationType: PLAINTEXT
    grpcPhotoClient:
      address: 'static://photo.rangiffler.dc:8096'
      negotiationType: PLAINTEXT
    grpcUserClient:
      address: 'static://userdata.rangiffler.dc:8090'
      negotiationType: PLAINTEXT

rangiffler-userdata:
  base-uri: 'http://userdata.rangiffler.dc:8089'
rangiffler-photo:
  base-uri: 'http://photo.rangiffler.dc:8095'
rangiffler-geo:
  base-uri: 'http://geo.rangiffler.dc:8085'
rangiffler-front:
  base-uri: 'http://frontend.rangiffler.dc'

