server:
  port: 8085
  error:
    include:
      message: true

grpc:
  server:
    port: 8086

spring:
  application:
    name: rangiffler-geo
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/rangiffler-geo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: false
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
#    org.springframework.boot.autoconfigure: DEBUG

  file:
    name: 'geo.log'

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rangiffler_geo'
    username: root
    password: secret
rangiffler-geo:
  base-uri: 'http://127.0.0.1:8085'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  datasource:
    url: 'jdbc:mysql://rangiffler-all-db:3306/rangiffler_geo'
    username: root
    password: secret
rangiffler-geo:
  base-uri: 'http://geo.rangiffler.dc:8085'
---
spring:
  config:
    activate:
      on-profile: 'prod'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      port: 443
      scheme: https
      uri: https://vault.qa.guru:443
      token: ${VAULT_TOKEN}
  kafka:
    bootstrap-servers: ${kafka.url}
    consumer:
      group-id: 'geo'
      auto-offset-reset: earliest
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
rangiffler-geo:
  base-uri: ${rangiffler-geo.url}
---
spring:
  config:
    activate:
      on-profile: 'staging'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      port: 443
      scheme: https
      uri: https://vault.qa.guru:443
      token: ${VAULT_TOKEN}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
rangiffler-geo:
  base-uri: ${rangiffler-geo.url}
---